### PR TITLE
FFA-24 Splash Screen

### PR DESCRIPTION
**Pull request by Coshiloco**
- Change logo of the Splash Screen

### CODE REVIEW

**Review by hgarciaalberto — CHANGES_REQUESTED** [review]
Can't this logo be a vector image?

**Comment by Coshiloco** [comment]
Hay un problema con la imagen del vector cuando la descargo y la paso a XML la imagen me sale en blanco no me carga por alguna razón

**Review by hgarciaalberto — APPROVED** [review]
Well Done! 🚀

**Comment by hgarciaalberto** [comment]
@rndevelo I've also seen that the blue color of "Forgot your password" doesn't much very well with the background, don't you think? 
image

**Pull request merged**
